service:
  description: handle data series into signals

server:
  port: 8088

signal:
  live-time-minutes: 30

cron:
  disable: "-"
  task:
    2H: "0 */10 9-23 * * MON-FRI"
    4H: "0 */10 9-23 * * MON-FRI"
    1D: "0 */20 9-23 * * MON-FRI"
    1W: "0 0 9-23 * * MON-FRI"